---
branches:
  only:
  - source
language: ruby
rvm:
- 1.9.3
before_script:
- git config user.name="Rogerz Zhang"
- git config user.email="rogerz.zhang@gmail.com"
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- rake setup_github_pages[$REPO_URL]
script:
- rake generate
after_script:
- rake deploy
env:
  global:
  - GH_REPO="rogerz/rogerz.github.com"
  - secure: "cSwATwZddJKGqmF48Ep4d793AoR/L1jWyI3UY0C1Iibki3ZAG0qJltFZSNLZ\n069af3y9RQ10420ihTi8ck0xjPbftncPyYLsiX2ni26l+uA2jwKSW8NG++/W\nKcQcTgXzzgyDzAEPPib9vr7Hk7tHsXkqTxcwPMmT0u4YCC8MRHs="
